ci(linter): comment-disable job summary, pr comments

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -41,85 +41,87 @@ jobs:
         uses: github/super-linter/slim@v5
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-        continue-on-error: true
+          # SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+        # continue-on-error: true
 
-      - name: Super-Linter Output Summary
-        run: |
-          echo "### 🐀 Super-Linter — \`${{ steps.linter.outcome }}\`" >> $GITHUB_STEP_SUMMARY
-          echo "<details><summary>Show Super-Linter Output</summary>" >> $GITHUB_STEP_SUMMARY
-          echo "" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
-          echo "${{ steps.linter.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-          echo "" >> $GITHUB_STEP_SUMMARY
-          echo "</details>" >> $GITHUB_STEP_SUMMARY
-        continue-on-error: true
+      # - name: Super-Linter Output Summary
+      #   run: |
+      #     echo "### 🐀 Super-Linter — \`${{ steps.linter.outcome }}\`" >> $GITHUB_STEP_SUMMARY
+      #     echo "<details><summary>Show Super-Linter Output</summary>" >> $GITHUB_STEP_SUMMARY
+      #     echo "" >> $GITHUB_STEP_SUMMARY
+      #     echo "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
+      #     echo "${{ steps.linter.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY
+      #     echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+      #     echo "" >> $GITHUB_STEP_SUMMARY
+      #     echo "</details>" >> $GITHUB_STEP_SUMMARY
+      #   continue-on-error: true
 
-      - name: Super-Linter Failure Summary
-        if: steps.linter.outcome == 'failure'
-        run: |
-          echo "#### ‼️ Lint Errors ‼️" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-          echo "${{ steps.linter.outputs.stderr }}" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-        continue-on-error: true
+      # - name: Super-Linter Failure Summary
+      #   if: steps.linter.outcome == 'failure'
+      #   run: |
+      #     echo "#### ‼️ Lint Errors ‼️" >> $GITHUB_STEP_SUMMARY
+      #     echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+      #     echo "${{ steps.linter.outputs.stderr }}" >> $GITHUB_STEP_SUMMARY
+      #     echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+      #   continue-on-error: true
 
-      - name: Update Pull Request
-        uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            // 1. Retrieve existing bot comments for the PR
-            const { data: comments } = await github.rest.issues.listComments({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number,
-            })
-            const botComment = comments.find(comment => {
-              return comment.user.type === 'Bot' && comment.body.includes('Show Super-Linter Output')
-            })
+      # - name: Update Pull Request
+      #   uses: actions/github-script@v6
+      #   if: github.event_name == 'pull_request'
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       // 1. Retrieve existing bot comments for the PR
+      #       const { data: comments } = await github.rest.issues.listComments({
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         issue_number: context.issue.number,
+      #       })
+      #       const botComment = comments.find(comment => {
+      #         return comment.user.type === 'Bot' && comment.body.includes('Show Super-Linter Output')
+      #       })
 
-            let linterAlerts = ('${{ steps.linter.outcome }}' == 'failure') ? `#### ‼️ Lint Errors ‼️
+      #       let linterAlerts = ('${{ steps.linter.outcome }}' == 'failure') ? `#### ‼️ Lint Errors ‼️
 
-              \`\`\`\n
-              ${{ steps.linter.outputs.stderr }}
-              \`\`\`
-              ` : '';
+      #         \`\`\`\n
+      #         ${{ steps.linter.outputs.stderr }}
+      #         \`\`\`
+      #         ` : '';
 
-            // 2. Prepare format of the comment
-            const output = `### 🐀 Super-Linter — \`${{ steps.linter.outcome }}\`
-            ${linterAlerts}
-            <details><summary>Show Super-Linter Output</summary>
+      #       // 2. Prepare format of the comment
+      #       const output = `### 🐀 Super-Linter — \`${{ steps.linter.outcome }}\`
+      #       ${linterAlerts}
+      #       <details><summary>Show Super-Linter Output</summary>
 
-            \`\`\`\n
-            ${{ steps.linter.outputs.stdout }}
-            \`\`\`
+      #       \`\`\`\n
+      #       ${{ steps.linter.outputs.stdout }}
+      #       \`\`\`
 
-            </details>
+      #       </details>
 
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
+      #       More info: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
-            // 3. If we have a comment, update it, otherwise create a new one
-            if (botComment) {
-              github.rest.issues.updateComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                comment_id: botComment.id,
-                body: output
-              })
-            } else {
-              github.rest.issues.createComment({
-                issue_number: context.issue.number,
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                body: output
-              })
-            }
+      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
 
-      - name: Super-Linter Status
-        if: steps.linter.outcome == 'failure'
-        run: |
-          echo "> ⚠️ Job failed. See errors for details." >> $GITHUB_STEP_SUMMARY
-          exit 1
+      #       // 3. If we have a comment, update it, otherwise create a new one
+      #       if (botComment) {
+      #         github.rest.issues.updateComment({
+      #           owner: context.repo.owner,
+      #           repo: context.repo.repo,
+      #           comment_id: botComment.id,
+      #           body: output
+      #         })
+      #       } else {
+      #         github.rest.issues.createComment({
+      #           issue_number: context.issue.number,
+      #           owner: context.repo.owner,
+      #           repo: context.repo.repo,
+      #           body: output
+      #         })
+      #       }
+
+      # - name: Super-Linter Status
+      #   if: steps.linter.outcome == 'failure'
+      #   run: |
+      #     echo "> ⚠️ Job failed. See errors for details." >> $GITHUB_STEP_SUMMARY
+      #     exit 1
