ci(terraform): unify workflows (dry)

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -5,6 +5,10 @@ name: Terraform
 on:
   workflow_call:
     inputs:
+      AWS_DEFAULT_REGION:
+        description: AWS Region
+        type: string
+        default: us-east-1
       version:
         description: Version of Terraform to use
         type: string
@@ -34,8 +38,20 @@ on:
         type: boolean
         default: false
     secrets:
+      AWS_ACCOUNT_ID:
+        required: false
+      AWS_ACCESS_KEY_ID:
+        required: false
+      AWS_SECRET_ACCESS_KEY:
+        required: false
       GH_TOKEN:
         required: true
+      NEW_RELIC_ACCOUNT_ID:
+        required: false
+      NEW_RELIC_API_KEY:
+        required: false
+      NEW_RELIC_REGION:
+        required: false
       SSH_PRIVATE_KEY:
         required: true
       TF_API_TOKEN:
@@ -45,8 +61,14 @@ permissions:
   contents: read
   pull-requests: write
 
-# env:
-#   GH_TOKEN: ${{ secrets.GH_TOKEN }}
+env:
+  AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
+  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
+  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
+  NEW_RELIC_REGION: ${{ secrets.NEW_RELIC_REGION }}
 
 jobs:
   terraform:
@@ -79,31 +101,67 @@ jobs:
           terraform_version: ${{ inputs.version }}
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
+      - name: Start Terraform Job Summary
+        run: echo "## Terraform — \`${{ inputs.working-directory }}\`" >> $GITHUB_STEP_SUMMARY
+
       - name: Terraform Format
         id: fmt
         if: inputs.format == true
         run: terraform fmt -check
+        continue-on-error: true
+
+      - name: Terraform Format Output Summary
+        run: echo "### ✏️ Terraform Format and Style — \`${{ steps.fmt.outcome }}\`" >> $GITHUB_STEP_SUMMARY
+
+      - name: Terraform Format Failure Summary
+        if: steps.fmt.outcome == 'failure'
+        run: |
+          echo "#### ‼️ Format Errors ‼️" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo "${{ steps.fmt.outputs.stderr }}" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
 
       - name: Terraform Init
         id: init
         run: terraform init
+        continue-on-error: true
+
+      - name: Terraform Initialization Output Summary
+        run: echo "### ⚙️ Terraform Initialization  — \`${{ steps.init.outcome }}\`" >> $GITHUB_STEP_SUMMARY
+
+      - name: Terraform Initialization Failure Summary
+        if: steps.init.outcome == 'failure'
+        run: |
+          echo "#### ‼️ Initialization Errors ‼️" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo "${{ steps.init.outputs.stderr }}" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
 
       - name: Terraform Validate
         id: validate
         if: inputs.validate == true
         run: terraform validate -no-color
+        continue-on-error: true
 
       - name: Terraform Validation Output Summary
-        id: validation_summary
         if: inputs.validate == true
         run: |
-          echo "### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`" >> $GITHUB_STEP_SUMMARY
-          echo "### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`" >> $GITHUB_STEP_SUMMARY
-          echo "### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo "### 🤖 Terraform Validation — \`${{ steps.validate.outcome }}\`" >> $GITHUB_STEP_SUMMARY
+          echo "<details><summary>Validation Output</summary>" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
           echo "${{ steps.validate.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY
           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-        continue-on-error: true
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "</details>" >> $GITHUB_STEP_SUMMARY
+
+      - name: Terraform Validation Failure Summary
+        if: steps.validate.outcome == 'failure'
+        run: |
+          echo "#### ‼️ Validation Errors ‼️" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo "${{ steps.validate.outputs.stderr }}" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
 
       - name: Terraform Plan
         id: plan
@@ -113,14 +171,24 @@ jobs:
         continue-on-error: true
 
       - name: Terraform Plan Output Summary
-        id: plan_summary
         if: inputs.plan == true
         run: |
-          echo "### Terraform Plan 📖\`${{ steps.plan.outcome }}\`" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo "### 📖 Terraform Plan — \`${{ steps.plan.outcome }}\`" >> $GITHUB_STEP_SUMMARY
+          echo "<details><summary>Show Plan</summary>" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
           echo "${{ steps.plan.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY
           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-        continue-on-error: true
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "</details>" >> $GITHUB_STEP_SUMMARY
+
+      - name: Terraform Plan Failure Summary
+        if: steps.plan.outcome == 'failure'
+        run: |
+          echo "#### ‼️ Plan Errors ‼️" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo "${{ steps.plan.outputs.stderr }}" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
 
       - name: Update Pull Request
         uses: actions/github-script@v6
@@ -137,13 +205,45 @@ jobs:
               issue_number: context.issue.number,
             })
             const botComment = comments.find(comment => {
-              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
+              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style') && comment.body.includes('${{ inputs.working-directory }}')
             })
 
+            let terraformFmtAlerts = ('${{ steps.fmt.outcome }}' == 'failure') ? `##### ‼️ ERRORS ‼️
+
+              \`\`\`\n
+              ${{ steps.fmt.outputs.stderr }}
+              \`\`\`
+              ` : '';
+
+            let terraformInitAlerts = ('${{ steps.init.outcome }}' == 'failure') ? `##### ‼️ ERRORS ‼️
+
+              \`\`\`\n
+              ${{ steps.init.outputs.stderr }}
+              \`\`\`
+              ` : '';
+
+            let terraformValidateAlerts = ('${{ steps.validate.outcome }}' == 'failure') ? `##### ‼️ ERRORS ‼️
+
+              \`\`\`\n
+              ${{ steps.validate.outputs.stderr }}
+              \`\`\`
+              ` : '';
+
+            let terraformPlanAlerts = ('${{ steps.plan.outcome }}' == 'failure') ? `##### ‼️ ERRORS ‼️
+
+              \`\`\`\n
+              ${{ steps.plan.outputs.stderr }}
+              \`\`\`
+              ` : '';
+
             // 2. Prepare format of the comment
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+            const output = `### Terraform — \`${{ inputs.working-directory }}\`
+            #### ✏️ Terraform Format and Style: \`${{ steps.fmt.outcome }}\`
+            ${terraformFmtAlerts}
+            #### ⚙️ Terraform Initialization: \`${{ steps.init.outcome }}\`
+            ${terraformInitAlerts}
+            #### 🤖 Terraform Validation: \`${{ steps.validate.outcome }}\`
+            ${terraformValidateAlerts}
             <details><summary>Validation Output</summary>
 
             \`\`\`\n
@@ -152,8 +252,8 @@ jobs:
 
             </details>
 
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-
+            #### 📖 Terraform Plan: \`${{ steps.plan.outcome }}\`
+            ${terraformPlanAlerts}
             <details><summary>Show Plan</summary>
 
             \`\`\`\n
@@ -182,8 +282,10 @@ jobs:
             }
 
       - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+        if: steps.plan.outcome == 'failure' || steps.validate.outcome == 'failure' || steps.init.outcome == 'failure' || steps.fmt.outcome == 'failure'
+        run: |
+          echo "> ⚠️ Job failed. See errors for details." >> $GITHUB_STEP_SUMMARY
+          exit 1
 
       - name: Terraform Apply
         # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
